# Setup
title: avicndugu.com
tagline: Wireless Technology
url: https://avicndugu.com
# paginate: 4
baseurl: ""
permalink: pretty

# Gems
# plugins:
 # - jekyll-gist
 # - jekyll-paginate
 # - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
#  ga_analytics: UA-xxxxxxx

# Specify the author for blog posts
author:
  name: Avic Ndugu
  url: avicndugu.com
  email: avicndugu1234@gmail.com

# Custom vars
version: 3.0.0
